### ISSUE TITLE
Respawn near death radius spawns into void

### ISSUE THREAD

**Issue by IsaiahHolman** [SirBlobman/RespawnX#1]
I have been testing out this plugin for respawning near the death point. I set the radius at 640, and found that the player was respawned below the world into the void.

Maybe this issue only happens at large radius' but I need a large radius because I want players to still have the immersion of "dying" so to speak, without having to walk all the way to their deathpoint from spawn. This is not possible with this plugin unfortunately

**Comment by SirBlobman** [comment]
Fixed in 3.0.0.13
