### ISSUE TITLE
Warning message in logs: The default language name is not properly defined.

### ISSUE THREAD

**Issue by serious-angel** [SirBlobman/RespawnX#2]
Dear Developers and Community,

Thank you for the project!

I am sorry, but apparently the following "warn" message frequently and periodically appears in the log of PaperMC (`git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)`):  

> `[RespawnX] The default language name is not properly defined.`

What might it be?

Best and kind regards

**Comment by SirBlobman** [comment]
Please send the following so we can help you better:

- `/about RespawnX`
- Your `language.yml` file for RespawnX

**Comment by SirBlobman** [comment]
@serious-angel  If you are still having these issue please resubmit. I have to close it as it has been more than one year.
